#!/bin/sh

# Create user and set permission
addgroup -g ${GID} selfoss && adduser -h /selfoss -s /bin/sh -D -G selfoss -u ${UID} selfoss

# Selfoss custom configuration file
rm /selfoss/config.ini

if [ -e /selfoss/data/config.ini ]; then
  cp /selfoss/data/config.ini /selfoss/config.ini
else
  cp /selfoss/defaults.ini /selfoss/config.ini
fi

# Init data dir
if [ ! "$(ls -A /selfoss/data)" ]; then
   cd /selfoss/data/ && mkdir cache favicons logs sqlite thumbnails
fi

# Set permissions
chown -R selfoss:selfoss /selfoss /var/run/php-fpm.sock /var/lib/nginx /tmp

# RUN !
supervisord -c /etc/supervisor/supervisord.conf
